from asignatura import lab_redes, web, pensamiento_creativo, programacion
from asignatura import sistemas_operativos, proyectos_1, matematica_discreta
from asignatura import programacion_objetos, estadistica, redes_ordenadores
from asignatura import composicion_visual, proyectos_2

from profesor import miguel_fernandez, ramona, bernardo, sergio, luis, ana, elena
from profesor import rodrigo, jorge, barbara, alfonso, hector, miguel_mesas
from profesor import carlos_gordon, carlos_vallez, constantino, ruben, eduardo, javier
from profesor import carlos_mora


class Clase:
    def __init__(self, dia, hora, asignatura, profesor, grupo):
        self.hora = hora
        self.dia = dia
        self.asignatura = asignatura
        self.profesor = profesor
        self.grupo = grupo

    def get_nombre_grupo(self):
        grupos = ["INSO1A", "INSO1B", "INSO1C", "INSO2A", "INSO2B", "INSO2C", "INSO2D"]
        return grupos[self.grupo]

    def __str__(self):
        hora_inicio_clase = 9 + self.hora * 2
        hora_fin_clase = hora_inicio_clase + 2

        return f"{hora_inicio_clase}:00 - {hora_fin_clase}:00 - {self.asignatura} - {self.profesor} - {self.grupo}"


clases_INSOA = [
    Clase(
        dia=0,
        hora=0,
        asignatura=lab_redes,
        profesor=miguel_fernandez,
        grupo=0
    ),
    Clase(
        dia=0,
        hora=1,
        asignatura=web,
        profesor=ramona,
        grupo=0
    ),
    Clase(
        dia=1,
        hora=1,
        asignatura=pensamiento_creativo,
        profesor=bernardo,
        grupo=0
    ),
    Clase(
        dia=1,
        hora=2,
        asignatura=programacion,
        profesor=sergio,
        grupo=0
    ),
    Clase(
        dia=2,
        hora=0,
        asignatura=proyectos_1,
        profesor=luis,
        grupo=0
    ),
    Clase(
        dia=2,
        hora=1,
        asignatura=matematica_discreta,
        profesor=ana,
        grupo=0
    ),
    Clase(
        dia=3,
        hora=0,
        asignatura=lab_redes,
        profesor=miguel_fernandez,
        grupo=0
    ),
    Clase(
        dia=3,
        hora=1,
        asignatura=matematica_discreta,
        profesor=ana,
        grupo=0
    ),
    Clase(
        dia=4,
        hora=1,
        asignatura=web,
        profesor=ramona,
        grupo=0
    ),
    Clase(
        dia=4,
        hora=2,
        asignatura=programacion,
        profesor=sergio,
        grupo=0
    ),
]

clases_INSOB = [
    Clase(
        dia=0,
        hora=1,
        asignatura=programacion,
        profesor=alfonso,
        grupo=1
    ),
    Clase(
        dia=0,
        hora=2,
        asignatura=lab_redes,
        profesor=hector,
        grupo=1
    ),
    Clase(
        dia=1,
        hora=1,
        asignatura=programacion,
        profesor=alfonso,
        grupo=1
    ),
    Clase(
        dia=1,
        hora=2,
        asignatura=web,
        profesor=ramona,
        grupo=1
    ),
    Clase(
        dia=2,
        hora=0,
        asignatura=web,
        profesor=ramona,
        grupo=1
    ),
    Clase(
        dia=2,
        hora=1,
        asignatura=matematica_discreta,
        profesor=jorge,
        grupo=1
    ),
    Clase(
        dia=3,
        hora=1,
        asignatura=pensamiento_creativo,
        profesor=barbara,
        grupo=1
    ),
    Clase(
        dia=3,
        hora=2,
        asignatura=lab_redes,
        profesor=hector,
        grupo=1
    ),
    Clase(
        dia=4,
        hora=0,
        asignatura=proyectos_1,
        profesor=luis,
        grupo=1
    ),
    Clase(
        dia=4,
        hora=1,
        asignatura=matematica_discreta,
        profesor=jorge,
        grupo=1
    )
]

clases_INSO1C = [
    Clase(
        dia=0,
        hora=1,
        asignatura=proyectos_1,
        profesor=luis,
        grupo=2
    ),
    Clase(
        dia=0,
        hora=2,
        asignatura=web,
        profesor=ramona,
        grupo=2
    ),
    Clase(
        dia=1,
        hora=1,
        asignatura=lab_redes,
        profesor=elena,
        grupo=2
    ),
    Clase(
        dia=1,
        hora=2,
        asignatura=programacion,
        profesor=rodrigo,
        grupo=2
    ),
    Clase(
        dia=2,
        hora=0,
        asignatura=matematica_discreta,
        profesor=jorge,
        grupo=2
    ),
    Clase(
        dia=2,
        hora=1,
        asignatura=lab_redes,
        profesor=elena,
        grupo=2
    ),
    Clase(
        dia=3,
        hora=1,
        asignatura=web,
        profesor=ramona,
        grupo=2
    ),
    Clase(
        dia=3,
        hora=2,
        asignatura=programacion,
        profesor=rodrigo,
        grupo=2
    ),
    Clase(
        dia=4,
        hora=0,
        asignatura=matematica_discreta,
        profesor=jorge,
        grupo=2
    ),
    Clase(
        dia=4,
        hora=1,
        asignatura=pensamiento_creativo,
        profesor=barbara,
        grupo=2
    )
]

clases_INSO2A = [
    Clase(
        dia=0,
        hora=4,
        asignatura=sistemas_operativos,
        profesor=carlos_vallez,
        grupo=3
    ),
    Clase(
        dia=0,
        hora=5,
        asignatura=programacion_objetos,
        profesor=miguel_mesas,
        grupo=3
    ),
    Clase(
        dia=1,
        hora=4,
        asignatura=estadistica,
        profesor=carlos_gordon,
        grupo=3
    ),
    Clase(
        dia=1,
        hora=5,
        asignatura=sistemas_operativos,
        profesor=carlos_vallez,
        grupo=3
    ),
    Clase(
        dia=2,
        hora=4,
        asignatura=redes_ordenadores,
        profesor=constantino,
        grupo=3
    ),
    Clase(
        dia=2,
        hora=5,
        asignatura=programacion_objetos,
        profesor=miguel_mesas,
        grupo=3
    ),
    Clase(
        dia=3,
        hora=3,
        asignatura=proyectos_2,
        profesor=eduardo,
        grupo=3
    ),
    Clase(
        dia=3,
        hora=4,
        asignatura=estadistica,
        profesor=carlos_gordon,
        grupo=3
    ),
    Clase(
        dia=4,
        hora=3,
        asignatura=composicion_visual,
        profesor=ruben,
        grupo=3
    ),
    Clase(
        dia=4,
        hora=4,
        asignatura=redes_ordenadores,
        profesor=constantino,
        grupo=3
    )
]

clases_INSO2B = [
    Clase(
        dia=0,
        hora=3,
        asignatura=sistemas_operativos,
        profesor=carlos_vallez,
        grupo=4
    ),
    Clase(
        dia=0,
        hora=4,
        asignatura=redes_ordenadores,
        profesor=constantino,
        grupo=4
    ),
    Clase(
        dia=1,
        hora=3,
        asignatura=sistemas_operativos,
        profesor=carlos_vallez,
        grupo=4
    ),
    Clase(
        dia=1,
        hora=4,
        asignatura=programacion_objetos,
        profesor=javier,
        grupo=4
    ),
    Clase(
        dia=2,
        hora=3,
        asignatura=estadistica,
        profesor=carlos_mora,
        grupo=4
    ),
    Clase(
        dia=2,
        hora=4,
        asignatura=programacion_objetos,
        profesor=javier,
        grupo=4
    ),
    Clase(
        dia=3,
        hora=3,
        asignatura=estadistica,
        profesor=carlos_mora,
        grupo=4
    ),
    Clase(
        dia=3,
        hora=4,
        asignatura=proyectos_2,
        profesor=eduardo,
        grupo=4
    ),
    Clase(
        dia=4,
        hora=3,
        asignatura=redes_ordenadores,
        profesor=constantino,
        grupo=4
    ),
    Clase(
        dia=4,
        hora=4,
        asignatura=composicion_visual,
        profesor=ruben,
        grupo=4
    )
]

clases_INSO2C = [
    Clase(
        dia=0,
        hora=3,
        asignatura=redes_ordenadores,
        profesor=constantino,
        grupo=5
    ),
    Clase(
        dia=0,
        hora=4,
        asignatura=sistemas_operativos,
        profesor=sergio,
        grupo=5
    ),
    Clase(
        dia=1,
        hora=3,
        asignatura=estadistica,
        profesor=carlos_mora,
        grupo=5
    ),
    Clase(
        dia=1,
        hora=4,
        asignatura=programacion_objetos,
        profesor=rodrigo,
        grupo=5
    ),
    Clase(
        dia=2,
        hora=3,
        asignatura=redes_ordenadores,
        profesor=constantino,
        grupo=5
    ),
    Clase(
        dia=2,
        hora=4,
        asignatura=estadistica,
        profesor=carlos_mora,
        grupo=5
    ),
    Clase(
        dia=3,
        hora=4,
        asignatura=programacion_objetos,
        profesor=rodrigo,
        grupo=5
    ),
    Clase(
        dia=3,
        hora=5,
        asignatura=proyectos_2,
        profesor=eduardo,
        grupo=5
    ),
    Clase(
        dia=4,
        hora=4,
        asignatura=sistemas_operativos,
        profesor=sergio,
        grupo=5
    ),
    Clase(
        dia=4,
        hora=5,
        asignatura=composicion_visual,
        profesor=ruben,
        grupo=5
    )
]

clases_INSO2D = [
    Clase(
        dia=1,
        hora=3,
        asignatura=estadistica,
        profesor=carlos_gordon,
        grupo=6
    ),
    Clase(
        dia=3,
        hora=3,
        asignatura=estadistica,
        profesor=carlos_gordon,
        grupo=6
        )
]
