from asignatura import lab_redes, web, pensamiento_creativo, programacion
from asignatura import sistemas_operativos, proyectos_1, matematica_discreta
from asignatura import programacion_objetos, estadistica, redes_ordenadores
from asignatura import composicion_visual, proyectos_2

from profesor import miguel_fernandez, ramona, bernardo, sergio, luis, ana, elena
from profesor import rodrigo, jorge, barbara, alfonso, hector, miguel_mesas
from profesor import carlos_gordon, carlos_vallez, constantino, ruben, eduardo, javier
from profesor import carlos_mora

from clase import Clase


class Horario:
    def __init__(self, nombre, clases):
        self.nombre = nombre
        self.clases = clases


clases_INSOA = [
    Clase(
        dia=0,
        hora=0,
        id_asignatura=lab_redes.id,
        profesor=miguel_fernandez.id,
        grupo=0
    ),
    Clase(
        dia=0,
        hora=1,
        id_asignatura=web.id,
        profesor=ramona.id,
        grupo=0
    ),
    Clase(
        dia=1,
        hora=1,
        id_asignatura=pensamiento_creativo.id,
        profesor=bernardo.id,
        grupo=0
    ),
    Clase(
        dia=1,
        hora=2,
        id_asignatura=programacion.id,
        profesor=sergio.id,
        grupo=0
    ),
    Clase(
        dia=2,
        hora=0,
        id_asignatura=proyectos_1.id,
        profesor=luis.id,
        grupo=0
    ),
    Clase(
        dia=2,
        hora=1,
        id_asignatura=matematica_discreta.id,
        profesor=ana.id,
        grupo=0
    ),
    Clase(
        dia=3,
        hora=0,
        id_asignatura=lab_redes.id,
        profesor=miguel_fernandez.id,
        grupo=0
    ),
    Clase(
        dia=3,
        hora=1,
        id_asignatura=matematica_discreta.id,
        profesor=ana.id,
        grupo=0
    ),
    Clase(
        dia=4,
        hora=1,
        id_asignatura=web.id,
        profesor=ramona.id,
        grupo=0
    ),
    Clase(
        dia=4,
        hora=2,
        id_asignatura=programacion.id,
        profesor=sergio.id,
        grupo=0
    ),
]

clases_INSOB = [
    Clase(
        dia=0,
        hora=1,
        id_asignatura=programacion.id,
        profesor=alfonso.id,
        grupo=1
    ),
    Clase(
        dia=0,
        hora=2,
        id_asignatura=lab_redes.id,
        profesor=hector.id,
        grupo=1
    ),
    Clase(
        dia=1,
        hora=1,
        id_asignatura=programacion.id,
        profesor=alfonso.id,
        grupo=1
    ),
    Clase(
        dia=1,
        hora=2,
        id_asignatura=web.id,
        profesor=ramona.id,
        grupo=1
    ),
    Clase(
        dia=2,
        hora=0,
        id_asignatura=web.id,
        profesor=ramona.id,
        grupo=1
    ),
    Clase(
        dia=2,
        hora=1,
        id_asignatura=matematica_discreta.id,
        profesor=jorge.id,
        grupo=1
    ),
    Clase(
        dia=3,
        hora=1,
        id_asignatura=pensamiento_creativo.id,
        profesor=barbara.id,
        grupo=1
    ),
    Clase(
        dia=3,
        hora=2,
        id_asignatura=lab_redes.id,
        profesor=hector.id,
        grupo=1
    ),
    Clase(
        dia=4,
        hora=0,
        id_asignatura=proyectos_1.id,
        profesor=luis.id,
        grupo=1
    ),
    Clase(
        dia=4,
        hora=1,
        id_asignatura=matematica_discreta.id,
        profesor=jorge.id,
        grupo=1
    )
]

clases_INSO1C = [
    Clase(
        dia=0,
        hora=1,
        id_asignatura=proyectos_1.id,
        profesor=luis.id,
        grupo=2
    ),
    Clase(
        dia=0,
        hora=2,
        id_asignatura=web.id,
        profesor=ramona.id,
        grupo=2
    ),
    Clase(
        dia=1,
        hora=1,
        id_asignatura=lab_redes.id,
        profesor=elena.id,
        grupo=2
    ),
    Clase(
        dia=1,
        hora=2,
        id_asignatura=programacion.id,
        profesor=rodrigo.id,
        grupo=2
    ),
    Clase(
        dia=2,
        hora=0,
        id_asignatura=matematica_discreta.id,
        profesor=jorge.id,
        grupo=2
    ),
    Clase(
        dia=2,
        hora=1,
        id_asignatura=lab_redes.id,
        profesor=elena.id,
        grupo=2
    ),
    Clase(
        dia=3,
        hora=1,
        id_asignatura=web.id,
        profesor=ramona.id,
        grupo=2
    ),
    Clase(
        dia=3,
        hora=2,
        id_asignatura=programacion.id,
        profesor=rodrigo.id,
        grupo=2
    ),
    Clase(
        dia=4,
        hora=0,
        id_asignatura=matematica_discreta.id,
        profesor=jorge.id,
        grupo=2
    ),
    Clase(
        dia=4,
        hora=1,
        id_asignatura=pensamiento_creativo.id,
        profesor=barbara.id,
        grupo=2
    )
]

clases_INSO2A = [
    Clase(
        dia=0,
        hora=4,
        id_asignatura=sistemas_operativos.id,
        profesor=carlos_vallez.id,
        grupo=3
    ),
    Clase(
        dia=0,
        hora=5,
        id_asignatura=programacion_objetos.id,
        profesor=miguel_mesas.id,
        grupo=3
    ),
    Clase(
        dia=1,
        hora=4,
        id_asignatura=estadistica.id,
        profesor=carlos_gordon.id,
        grupo=3
    ),
    Clase(
        dia=1,
        hora=5,
        id_asignatura=sistemas_operativos.id,
        profesor=carlos_vallez.id,
        grupo=3
    ),
    Clase(
        dia=2,
        hora=4,
        id_asignatura=redes_ordenadores.id,
        profesor=constantino.id,
        grupo=3
    ),
    Clase(
        dia=2,
        hora=5,
        asignaturas_asignadas=programacion_objetos.id,
        profesor=miguel_mesas.id,
        grupo=3
    ),
    Clase(
        dia=3,
        hora=3,
        id_asignatura=proyectos_2.id,
        profesor=eduardo.id,
        grupo=3
    ),
    Clase(
        dia=3,
        hora=4,
        id_asignatura=estadistica.id,
        profesor=carlos_gordon.id,
        grupo=3
    ),
    Clase(
        dia=4,
        hora=3,
        id_asignatura=composicion_visual.id,
        profesor=ruben.id,
        grupo=3
    ),
    Clase(
        dia=4,
        hora=4,
        id_asignatura=redes_ordenadores.id,
        profesor=constantino.id,
        grupo=3
    )
]

clases_INSO2B = [
    Clase(
        dia=0,
        hora=3,
        id_asignatura=sistemas_operativos.id,
        profesor=carlos_vallez.id,
        grupo=4
    ),
    Clase(
        dia=0,
        hora=4,
        id_asignatura=redes_ordenadores.id,
        profesor=constantino.id,
        grupo=4
    ),
    Clase(
        dia=1,
        hora=3,
        id_asignatura=sistemas_operativos.id,
        profesor=carlos_vallez.id,
        grupo=4
    ),
    Clase(
        dia=1,
        hora=4,
        id_asignatura=programacion_objetos.id,
        profesor=javier.id,
        grupo=4
    ),
    Clase(
        dia=2,
        hora=3,
        id_asignatura=estadistica.id,
        profesor=carlos_mora.id,
        grupo=4
    ),
    Clase(
        dia=2,
        hora=4,
        id_asignatura=programacion_objetos.id,
        profesor=javier.id,
        grupo=4
    ),
    Clase(
        dia=3,
        hora=3,
        id_asignatura=estadistica.id,
        profesor=carlos_mora.id,
        grupo=4
    ),
    Clase(
        dia=3,
        hora=4,
        id_asignatura=proyectos_2.id,
        profesor=eduardo.id,
        grupo=4
    ),
    Clase(
        dia=4,
        hora=3,
        id_asignatura=redes_ordenadores.id,
        profesor=constantino.id,
        grupo=4
    ),
    Clase(
        dia=4,
        hora=4,
        id_asignatura=composicion_visual.id,
        profesor=ruben.id,
        grupo=4
    )
]

clases_INSO2C = [
    Clase(
        dia=0,
        hora=3,
        id_asignatura=redes_ordenadores.id,
        profesor=constantino.id,
        grupo=5
    ),
    Clase(
        dia=0,
        hora=4,
        id_asignatura=sistemas_operativos.id,
        profesor=sergio.id,
        grupo=5
    ),
    Clase(
        dia=1,
        hora=3,
        id_asignatura=estadistica.id,
        profesor=carlos_mora.id,
        grupo=5
    ),
    Clase(
        dia=1,
        hora=4,
        id_asignatura=programacion_objetos.id,
        profesor=rodrigo.id,
        grupo=5
    ),
    Clase(
        dia=2,
        hora=3,
        id_asignatura=redes_ordenadores.id,
        profesor=constantino.id,
        grupo=5
    ),
    Clase(
        dia=2,
        hora=4,
        id_asignatura=estadistica.id,
        profesor=carlos_mora.id,
        grupo=5
    ),
    Clase(
        dia=3,
        hora=4,
        id_asignatura=programacion_objetos.id,
        profesor=rodrigo.id,
        grupo=5
    ),
    Clase(
        dia=3,
        hora=5,
        id_asignatura=proyectos_2.id,
        profesor=eduardo.id,
        grupo=5
    ),
    Clase(
        dia=4,
        hora=4,
        id_asignatura=sistemas_operativos.id,
        profesor=sergio.id,
        grupo=5
    ),
    Clase(
        dia=4,
        hora=5,
        id_asignatura=composicion_visual.id,
        profesor=ruben.id,
        grupo=5
    )
]

clases_INSO2D = [
    Clase(
        dia=1,
        hora=3,
        id_asignatura=estadistica.id,
        profesor=carlos_gordon.id,
        grupo=6
    ),
    Clase(
        dia=3,
        hora=3,
        id_asignatura=estadistica.id,
        profesor=carlos_gordon.id,
        grupo=6
        )
]

horario_INSOA = Horario("INSOA", clases_INSOA)
horario_INSOB = Horario("INSOB", clases_INSOB)
horario_INSO1C = Horario("INSO1C", clases_INSO1C)
horario_INSO2A = Horario("INSO2A", clases_INSO2A)
horario_INSO2B = Horario("INSO2B", clases_INSO2B)
horario_INSO2C = Horario("INSO2C", clases_INSO2C)
horario_INSO2D = Horario("INSO2D", clases_INSO2D)
